#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# apnic-extended reference: http://ftp.apnic.net/apnic/stats/apnic/README-EXTENDED.TXT
#

import os.path
import tempfile
import urllib.request

import sys

DATA_FILE_URL = "http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-extended-latest"
target_file = os.path.abspath("net/geoip/geodata.go")


def ip_to_uint(ipStr):
    ipV = 0

    i = 3
    for ele in ipStr.split("."):
        currentV = int(ele)
        if i > 0:
            ipV += currentV << i * 8
        i -= 1
    return ipV


def parse_apnic_extended_file(f_in, f_out, onlyIPv4=True, onlyCN=True):
    f_out.write(
        '''
        // Generated by geodata-gen.py


        package geoip
        import (
            "github.com/FTwOoO/vpncore/net/addr"
            "net"
        )

        func GeoIpQuery(ip string) string {
            r := GeoIPData.Get(net.ParseIP(ip).To4())
            if r != nil {
                return r.Group
            }
            return ""
        }

        var GeoIPData = addr.IPRanges{
        ''')

    for line in f_in:
        arr = line.split("|")
        if arr[0] != 'apnic' or arr[-1].strip() == 'summary':
            continue

        if len(arr) < 7:
            continue

        country = arr[1]
        type = arr[2]
        startIp = arr[3]
        count = int(arr[4])
        status = arr[6]

        if type in ['ipv4', 'ipv6'] and status in ['available', 'allocated', 'assigned', 'reserved']:
            if status not in ['allocated', 'assigned']:
                continue

            if country.strip() == "":
                continue

            if onlyCN and country != "CN":
                continue

            if onlyIPv4 and type != 'ipv4':
                continue

            ipStart = ip_to_uint(startIp)
            ipEnd = ipStart + count - 1

            f_out.write('''\t&addr.IPRange{Start:0x%x, End:0x%x, Group:"%s", Version:addr.IPv4},\n ''' % (ipStart, ipEnd, country))

    f_out.write("}")


if __name__ == '__main__':

    with open(target_file, 'w') as f_out:
        try:
            #req = urllib.request.urlopen(DATA_FILE_URL)
            req = open("/Users/ganxiangle/Workspaces/delegated-apnic-extended-latest", 'rb')
        except:
            print("Get data file fail from %s" % DATA_FILE_URL)
            sys.exit(1)

        f_in = tempfile.TemporaryFile("w+")
        f_in.write(req.read().decode('utf-8'))
        f_in.seek(0)

        parse_apnic_extended_file(f_in, f_out, onlyCN=True)
